-- Table: public.AdminMemberStatus

-- DROP TABLE IF EXISTS public."AdminMemberStatus";

CREATE TABLE IF NOT EXISTS public."AdminMemberStatus"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AdminMemberStatus" PRIMARY KEY ("Id")
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."AdminMemberStatus"
    OWNER to pg13;



-- Table: public.AdminMember

-- DROP TABLE IF EXISTS public."AdminMember";

CREATE TABLE IF NOT EXISTS public."AdminMember"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Guid" text COLLATE pg_catalog."default" NOT NULL,
    "UserName" text COLLATE pg_catalog."default" NOT NULL,
    "Email" text COLLATE pg_catalog."default" NOT NULL,
    "Account" text COLLATE pg_catalog."default" NOT NULL,
    "Pwd" text COLLATE pg_catalog."default" NOT NULL,
    "StatusId" integer NOT NULL,
    "ErrorTimes" integer NOT NULL,
    "LastLoginDate" timestamp with time zone NOT NULL,
    "IsMaster" boolean NOT NULL DEFAULT false,
    "HashSalt" text COLLATE pg_catalog."default" NOT NULL,
    "ExpirationDate" timestamp with time zone NOT NULL,
    "CreateDate" timestamp with time zone NOT NULL,
    "UpdateDate" timestamp with time zone,
    CONSTRAINT "PK_AdminMember" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdminMember_StatusId_To_AdminMemberStatus_Id" FOREIGN KEY ("StatusId")
    REFERENCES public."AdminMemberStatus" ("Id") MATCH SIMPLE
                           ON UPDATE NO ACTION
                           ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."AdminMember"
    OWNER to pg13;
-- Index: IX_AdminMember_Guid

-- DROP INDEX IF EXISTS public."IX_AdminMember_Guid";

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AdminMember_Guid"
    ON public."AdminMember" USING btree
    ("Guid" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_AdminMember_StatusId

-- DROP INDEX IF EXISTS public."IX_AdminMember_StatusId";

CREATE INDEX IF NOT EXISTS "IX_AdminMember_StatusId"
    ON public."AdminMember" USING btree
    ("StatusId" ASC NULLS LAST)
    TABLESPACE pg_default;